#!/bin/bash

usage () {
  echo "Usage: $0 FILE" >&2
  exit 1
}

ircpass () {
USERNAME=$USER
ATTRIBUTE=ircPassword
LDAPBASE="cn=users,dc=carmen,dc=int,dc=sto,dc=spotify,dc=net"
BINDUSER="uid=$USERNAME,$LDAPBASE"
LDAPHOST='haldap.spotify.net'
echo -n "Enter your LDAP Password: "
read -s BINDPW
echo
echo Now create a new password that is different than your ldap password
IRCPASS=$(openssl passwd -1)
}

testpass () {
declare -a hash
irchash=($(echo $IRCPASS | cut -f3,4 -d\$ |sed 's/\$/ /g' ))
ldaphash=($(echo $BINDPW | openssl passwd -1 -stdin -salt ${irchash[0]} | cut -f3,4 -d\$ | sed 's/\$/ /g' ))

if [ "${irchash[1]}" == "${ldaphash[1]}" ] ; then
  echo "Fail! Your IRC password should not be the same as your LDAP password"
  exit 1
fi
}

updateldap() {
echo \
"dn: $BINDUSER
changetype: modify
replace: $ATTRIBUTE
$ATTRIBUTE: $IRCPASS" \
\
| ldapmodify -vv -c -x -h $LDAPHOST -D "$BINDUSER" -w "$BINDPW" &>/dev/null && echo "Success! Your IRC password was updated." || echo "FAIL! Your IRC password was not updated."
}

if [ "$#" -ne 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  usage
fi


ircpass && testpass && updateldap
